apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: azure-keyvault-e2e
  namespace: poc-dev
spec:
  interval: 1m
  chart:
    spec:
      chart: azure-keyvault-e2e
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: azure-repo
        namespace: flux-system
  values:
    replicaCount: 1
