apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: azure-keyvault-e2e
  namespace: poc-dev
spec:
  imageRepositoryRef:
    name: azure-keyvault-e2e
  filterTags:
    pattern: '^\d{14}$'
    extract: "$0"
  policy:
    numerical:
      order: desc
