apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: azure-keyvault-e2e
  namespace: poc-dev
spec:
  image: saipocregistry.azurecr.io/azure-keyvault-e2e
  interval: 1m0s
  secretRef:
    name: image-pull-secret
