apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: azure-keyvault-e2e
  namespace: poc-dev
spec:
  imageRepositoryRef:
    name: azure-keyvault-e2e
  policy:
    alphabetical:
      order: asc
