apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- image.yaml
- image-policy.yaml
- image-update.yaml
- helmrelease.yaml
patchesStrategicMerge:
- patch-helm-release.yaml
