apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- image.yaml
- image-policy.yaml
- image-update.yaml
- gitrepository.yaml
- ../../../apps/base/azure-keyvault-e2e/helm-release.yaml
patchesStrategicMerge:
- patch-helm-release.yaml
