apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-e2e
  namespace: poc-dev
spec:
  values:
    image:
      repository: saipocregistry.azurecr.io/azure-keyvault-e2e
      tag: "20250220223620"  # Manually updating image tag
