apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/dev # Path relative to Git repository root
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: flux-system
  targetNamespace: poc-dev
  timeout: 2m
  patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: azure-keyvault-e2e
      spec:
        values:
          replicaCount: 2  # Example patching Helm values
    target:
      kind: HelmRelease
      name: azure-keyvault-e2e
