apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-e2e
  namespace: poc-uat
spec:
  values:
    image:
      tag: latest # {"$imagepolicy": "azure-keyvault-e2e:tag"}
