apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: azure-keyvault-e2e
  namespace: poc-dev
spec:
  releaseName: azure-keyvault-e2e
  interval: 5m
  timeout: 3m
  chart:
    spec:
      chart: azure-keyvault-e2e
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: azure-keyvault-repo
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    image:
      repository: saipocregistry.azurecr.io/azure-keyvault-e2e
      tag: "latest"
