apiVersion: v1
kind: Secret
metadata:
  name: azure-acr-auth
  namespace: flux-system
  labels:
    app.kubernetes.io/name: azure-acr-auth
    app.kubernetes.io/managed-by: fluxcd
  annotations:
    kubernetes.io/service-account.name: azure-acr-auth
    kubernetes.io/service-account.namespace: flux-system

type: Opaque
stringData:
  clientId: <YOUR_SP_CLIENT_ID>
  clientSecret: <YOUR_SP_CLIENT_SECRET>
  tenantId: <YOUR_SP_TENANT_ID>
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-pull-secret
  namespace: flux-system
type: Opaque
stringData:
  username: <YOUR_SP_CLIENT_ID>
  password: <YOUR_SP_CLIENT_SECRET>
---
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  namespace: poc-dev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"<YOUR_ACR_NAME>.azurecr.io":{"username":"<YOUR_SP_CLIENT_ID>","password":"<YOUR_SP_CLIENT_SECRET>"}}}'
---
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  namespace: poc-uat
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"<YOUR_ACR_NAME>.azurecr.io":{"username":"<YOUR_SP_CLIENT_ID>","password":"<YOUR_SP_CLIENT_SECRET>"}}}'
