apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 1m
  path: ./uat
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: flux-system
  targetNamespace: poc-uat
  patches:
  - path: azure-keyvault-e2e/patch-helm-release.yaml
  resources:
  - azure-keyvault-e2e/image.yaml
  - azure-keyvault-e2e/image-policy.yaml
  - azure-keyvault-e2e/image-update.yaml
  - ../../apps/base/azure-keyvault-e2e
