apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uat
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/uat # Points to the directory containing kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: flux-system
  targetNamespace: poc-deuatv
  patches:
  - target:
      kind: HelmRelease
      name: azure-keyvault-e2e
    patch: | # <-- Using inline patch instead of "path"
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: azure-keyvault-e2e
      spec:
        values:
          replicaCount: 2  # Example patching Helm values
  timeout: 2m
