apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aks
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/aks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: flux-system
